### ISSUE TITLE
NPM Package Update

### ISSUE THREAD

**Issue by jarroda** [DavidRouyer/grunt-aspnet-server#1]
Hey, thanks for this grunt task - its exactly what I'm looking for.  I notice you have made the necessary changes for beta7, are you planning on updating the NPM package?  Thanks.

**Comment by DavidRouyer** [comment]
Sorry, I'm new to npm, I thought it would publish new tags automatically.
I added a tag for the last changes and I published it on npm.

Enjoy ! ;)

If you have any ideas for new features, don't hesitate, ping me !

**Comment by jarroda** [comment]
Fantastic, thanks!
